alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias c='clear'
alias h='cd ~/'
alias hc='h && c'
alias back='cd $OLDPWD'
alias ff='find . -type f -name'
alias fd='find . -type d -name'
alias now='date +%T'
alias artisan='php artisan'
alias migrate='php artisan migrate'
alias pu='vendor/bin/phpunit'
alias puf='vendor/bin/phpunit --filter '
alias puc='vendor/bin/phpunit --log-junit="./reports/phpunit/junit.xml" --coverage-html="./reports/phpunit/coverage" --testdox-html="./reports/phpunit/testdox"'
alias pamt='php artisan make:test'
alias pmetrics='phpmetrics app --report-html="./reports/phpmetrics" --git --report-violations="./reports/phpmetrics/violations.xml" --junit="./reports/phpunit/junit.xml"'
alias initproject='bash /root/larastart.sh'